const text = [
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec pharetra nisl. Donec eleifend fermentum mauris, vel aliquam justo luctus sed. Aenean congue massa sed dolor tempus, vitae fermentum turpis accumsan. Phasellus imperdiet tempus consectetur. Morbi blandit tellus in nunc mollis aliquam. Vestibulum vitae diam tristique, ornare lectus vitae, finibus mauris. Integer eu accumsan purus. Integer risus quam, hendrerit a eros non, lobortis pretium massa.`,
  `Nullam sit amet elit erat. Donec pulvinar arcu hendrerit libero venenatis, vel dictum nisl fringilla. Pellentesque tempus sem eget lectus bibendum, eget vulputate orci placerat. Fusce condimentum augue id ligula imperdiet, a porttitor lacus egestas. Morbi semper maximus risus, tempor gravida quam laoreet ac. Phasellus eget nisl in magna lacinia ultrices in eget urna. Pellentesque a venenatis nulla. Aenean at velit ex. Cras egestas ac quam nec imperdiet. In hac habitasse platea dictumst. Vivamus eu auctor diam.`,
  `Curabitur consectetur faucibus massa, in cursus enim tincidunt in. Donec tempus at nunc eget venenatis. Aenean blandit nisi quis felis ornare euismod. Etiam euismod nulla in accumsan pellentesque. In non tortor sapien. Suspendisse laoreet consectetur dictum. Ut pretium in ex gravida maximus. Quisque turpis ligula, sodales nec leo sit amet, ornare gravida mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam ac accumsan odio. In libero lectus, porttitor id lectus id, dignissim iaculis neque.`,
  `Praesent lobortis ornare quam, sed facilisis nisl ultricies at. Etiam rutrum scelerisque ultrices. Vestibulum in ligula eu felis imperdiet dignissim. Praesent ut venenatis metus, quis hendrerit sem. Maecenas fringilla arcu sodales tortor faucibus, et accumsan ipsum scelerisque. Phasellus nec egestas mauris. Praesent tristique elit vel orci ornare, vitae feugiat quam porta. Duis venenatis lobortis risus sed pulvinar. Sed quis lectus sed sem dignissim malesuada. Aliquam erat volutpat. Curabitur quis magna lectus. Sed porta fringilla orci, at semper sem mattis eu. Vestibulum ultricies pharetra sapien in lobortis.`,
  `Nulla facilisi. Morbi at dolor ac nisi imperdiet eleifend. Nullam luctus consectetur quam ut porttitor. Pellentesque in sapien sit amet diam ornare convallis. Donec malesuada velit vitae vehicula porttitor. Pellentesque bibendum nunc ultricies, malesuada mi in, convallis eros. Vivamus sodales nec elit at aliquet. Curabitur id erat non libero gravida rutrum. In condimentum massa ut elementum lobortis. Nullam eu magna in velit suscipit venenatis eget ut libero. Morbi lacinia lorem sit amet vehicula ultricies. Phasellus erat eros, euismod ut blandit eu, hendrerit quis ipsum.`,
  `Vestibulum lobortis dolor at leo suscipit tincidunt. Etiam eu lectus finibus, ultrices mi porta, lacinia nulla. Quisque tempor, mi a mattis scelerisque, neque dui consequat arcu, sit amet tincidunt magna nunc semper justo. Sed ultricies efficitur leo sit amet viverra. Donec facilisis euismod ipsum. Maecenas arcu erat, euismod ut fermentum non, pulvinar at dolor. Vestibulum sit amet arcu quis magna lobortis blandit. Nulla ornare lectus ut imperdiet ornare. In finibus feugiat lorem sit amet sagittis. Praesent lacinia quam vitae turpis posuere tempor vel eu nibh. Nulla dapibus diam et risus sollicitudin convallis. Aliquam facilisis facilisis purus, nec placerat orci auctor nec. Phasellus ultrices metus hendrerit libero vulputate egestas in eget mauris. Donec pretium vulputate porttitor. Morbi odio diam, ullamcorper quis odio at, venenatis pellentesque urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
  `In malesuada pellentesque massa, nec maximus dui consectetur nec. Fusce condimentum enim metus, in pretium tellus egestas vel. Fusce ac nunc arcu. Cras eu ex sagittis, lobortis massa ut, imperdiet enim. Nunc hendrerit fermentum leo vitae sagittis. Sed eu ante sit amet neque fringilla tincidunt at et nisi. Sed et libero nulla. Nullam eleifend nisi cursus, scelerisque lacus sit amet, ultrices felis. Sed non justo vitae lacus feugiat placerat. Morbi accumsan nisi non ex bibendum, et tempor nisi congue. Maecenas congue nulla eget semper consectetur. Cras gravida eros non dolor pharetra malesuada. Pellentesque massa ipsum, ultricies sit amet dignissim non, dictum vel libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;`,
  `Mauris sed odio nec justo blandit aliquam. Donec posuere at urna eget tincidunt. Donec aliquet lorem eu turpis gravida, vitae pulvinar nulla congue. Cras eget molestie orci. Praesent scelerisque sapien lorem, ut hendrerit turpis congue quis. Curabitur nec egestas turpis, vitae interdum lacus. Donec quis rutrum dui. Nunc et vulputate nunc, quis viverra ipsum. Nunc hendrerit eget risus vel lobortis.`,
  `Fusce quis enim vitae lorem consectetur efficitur vitae id libero. Aenean egestas eros ac sapien iaculis volutpat. Aenean fringilla efficitur mi, id fringilla quam tristique id. Vestibulum ornare orci eget felis vulputate, sit amet ornare ipsum feugiat. Aliquam erat volutpat. Aenean viverra blandit turpis vel convallis. Nunc sodales sodales dui, nec vehicula nunc hendrerit quis. Maecenas varius consequat ante vitae aliquet.`,
  `Ut semper, mi a fringilla suscipit, dui lorem congue lacus, vitae sollicitudin nisi quam vel ligula. Donec dignissim convallis magna nec luctus. Nunc mollis tristique accumsan. Mauris venenatis leo id risus vestibulum suscipit. Donec viverra elementum justo vel accumsan. Aenean consequat nunc ac augue elementum, eget tincidunt ligula egestas. Donec justo velit, rhoncus eu ligula at, euismod congue arcu. Phasellus luctus tellus non lacus venenatis, et gravida massa condimentum. Aliquam consectetur, tellus in aliquam mollis, sem orci elementum mauris, in efficitur tellus leo in lacus. Suspendisse sit amet magna ligula. Donec id cursus lacus. Proin neque libero, aliquam et mauris quis, facilisis porttitor ex. Sed convallis, dolor ut vestibulum malesuada, nulla arcu convallis dolor, rutrum auctor nunc massa id justo.`,
];

export default text;